# Generated by Django 4.1.5 on 2023-04-07 09:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_myorders_orderitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
