# Generated by Django 4.1.5 on 2023-04-10 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_myorders_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myorders',
            name='review',
        ),
        migrations.AddField(
            model_name='orderitems',
            name='review',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
