# Generated by Django 4.1.5 on 2023-03-21 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='custuser',
            old_name='addess',
            new_name='address',
        ),
    ]
