# Generated by Django 4.1.5 on 2023-03-24 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_rename_addess_custuser_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custuser',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
